branches:
  only: ['(none)']

image: 'Visual Studio 2017'

platform: 'x64'

build: false

cache:
- 'C:\Miniconda36-x64\pkgs'
- '%LOCALAPPDATA%\pip\Cache'

install:
- ps: |
    # begin-syntax: ps1
    $Env:PATH = "C:\Miniconda36-x64;C:\Miniconda36-x64\Scripts;$Env:PATH"
    $Env:PYTHONUNBUFFERED = 1
    conda config --set always_yes true
    conda update --quiet --all
    python -mpip install -U pip
    .\tools\build-windows-wheel.ps1
    python -mpip install $(Get-Item dist\*.whl)
    $host.SetShouldExit($LastExitCode)  # The only thing that matters, regardless of stderr.
    # end-syntax: ps1

test_script:
- ps: |
    # begin-syntax: ps1
    $Env:PATH = "C:\Miniconda36-x64;$Env:PATH"
    $Env:MPLBACKEND = "module://mplcairo.base"
    python -c "import os; from pylab import *; gca(); savefig(os.devnull, format='png')"
    # end-syntax: ps1

artifacts:
- path: dist\*.whl

on_finish: |
  conda clean --packages
